# Generated by Django 5.1.4 on 2025-01-01 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='media_files',
        ),
        migrations.RemoveField(
            model_name='post',
            name='object_3d_files',
        ),
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='post_media/', verbose_name='Медіа файли')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='posts.post')),
            ],
        ),
        migrations.CreateModel(
            name='Object3DFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='post_3d_objects/', verbose_name="Файли 3D об'єктів")),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_3d_files', to='posts.post')),
            ],
        ),
    ]
