# Generated by Django 5.1.4 on 2025-01-02 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_remove_post_media_files_remove_post_object_3d_files_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('home', 'Для дому'), ('hobby', 'Хобі та творчість'), ('kids', 'Для дітей'), ('gadgets', 'Гаджети та аксесуари'), ('tools', 'Інструменти та функціональні речі'), ('printers', 'Для 3D-принтерів')], default='home', max_length=20, verbose_name='Категорія'),
        ),
    ]
