# Generated by Django 5.1.4 on 2025-02-19 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_remove_comment_text_comment_content_comment_cubes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_sanctuary',
            field=models.BooleanField(default=False, verbose_name='Убежище'),
        ),
    ]
