# Generated by Django 5.1.4 on 2025-02-19 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_comment_is_sanctuary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='is_sanctuary',
        ),
    ]
