# Generated by Django 5.1.4 on 2025-02-11 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
