# Generated by Django 5.1.4 on 2025-02-19 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_reset_code_user_reset_code_expires'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_sanctuary_enabled',
            field=models.BooleanField(default=False, verbose_name='Фільтр коментарів (Убежище)'),
        ),
    ]
