# Generated by Django 5.1.4 on 2025-01-03 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_type', models.CharField(choices=[('PLA', 'PLA'), ('ABS', 'ABS'), ('PETG', 'PETG'), ('Nylon', 'Nylon'), ('Resin', 'Resin'), ('Other', 'Інші')], max_length=10)),
                ('material_color', models.CharField(choices=[('Black', 'Чорний'), ('White', 'Білий'), ('Blue', 'Синій'), ('Red', 'Червоний'), ('Green', 'Зелений'), ('Yellow', 'Жовтий')], max_length=10)),
                ('height', models.FloatField()),
                ('width', models.FloatField()),
                ('depth', models.FloatField()),
                ('resolution', models.CharField(choices=[('High', 'Висока'), ('Medium', 'Середня'), ('Low', 'Низька')], max_length=50)),
                ('support_structure', models.CharField(choices=[('With Support', 'З підтримками'), ('Without Support', 'Без підтримок')], max_length=50)),
                ('post_processing', models.CharField(choices=[('None', 'Без обробки'), ('Sandblasting', 'Піскоструминна обробка'), ('Painting', 'Лакування'), ('Pre-Painting', 'Підготовка до фарбування')], max_length=50)),
                ('copies', models.PositiveIntegerField(default=1)),
                ('delivery_time', models.CharField(choices=[('Urgent', 'Терміновий'), ('Standard', 'Стандартний'), ('By Agreement', 'За попереднім погодженням')], max_length=50)),
                ('comments', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='order_files/')),
                ('file_name', models.CharField(max_length=255)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='orders.order')),
            ],
        ),
    ]
