# Generated by Django 5.1.4 on 2025-01-03 15:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='copies',
        ),
        migrations.RemoveField(
            model_name='order',
            name='depth',
        ),
        migrations.RemoveField(
            model_name='order',
            name='height',
        ),
        migrations.RemoveField(
            model_name='order',
            name='material_color',
        ),
        migrations.RemoveField(
            model_name='order',
            name='material_type',
        ),
        migrations.RemoveField(
            model_name='order',
            name='post_processing',
        ),
        migrations.RemoveField(
            model_name='order',
            name='resolution',
        ),
        migrations.RemoveField(
            model_name='order',
            name='support_structure',
        ),
        migrations.RemoveField(
            model_name='order',
            name='width',
        ),
        migrations.AddField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Час створення'),
        ),
        migrations.AddField(
            model_name='order',
            name='title',
            field=models.CharField(default=0, max_length=255, verbose_name='Назва замовлення'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='comments',
            field=models.TextField(default=0, verbose_name='Коментарі'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_time',
            field=models.CharField(choices=[('Urgent', 'Терміновий'), ('Standard', 'Стандартний'), ('By Agreement', 'За попереднім погодженням')], default='Standard', max_length=50),
        ),
        migrations.AlterField(
            model_name='orderfile',
            name='file_name',
            field=models.CharField(max_length=255, verbose_name='Назва файлу'),
        ),
        migrations.CreateModel(
            name='ModelCharacteristics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_type', models.CharField(choices=[('PLA', 'PLA'), ('ABS', 'ABS'), ('PETG', 'PETG'), ('Nylon', 'Nylon'), ('Resin', 'Resin'), ('Other', 'Інші')], max_length=10)),
                ('material_color', models.CharField(choices=[('Black', 'Чорний'), ('White', 'Білий'), ('Blue', 'Синій'), ('Red', 'Червоний'), ('Green', 'Зелений'), ('Yellow', 'Жовтий')], max_length=10)),
                ('height', models.FloatField()),
                ('width', models.FloatField()),
                ('depth', models.FloatField()),
                ('resolution', models.CharField(choices=[('High', 'Висока'), ('Medium', 'Середня'), ('Low', 'Низька')], max_length=50)),
                ('support_structure', models.CharField(choices=[('With Support', 'З підтримками'), ('Without Support', 'Без підтримок')], max_length=50)),
                ('post_processing', models.CharField(choices=[('None', 'Без обробки'), ('Sandblasting', 'Піскоструминна обробка'), ('Painting', 'Лакування'), ('Pre-Painting', 'Підготовка до фарбування')], max_length=50)),
                ('copies', models.PositiveIntegerField(default=1)),
                ('order_file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='characteristics', to='orders.orderfile')),
            ],
        ),
    ]
