# Generated by Django 5.1.4 on 2025-01-03 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_copies_remove_order_depth_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelcharacteristics',
            old_name='depth',
            new_name='size',
        ),
        migrations.RemoveField(
            model_name='modelcharacteristics',
            name='height',
        ),
        migrations.RemoveField(
            model_name='modelcharacteristics',
            name='width',
        ),
    ]
