# Generated by Django 5.1.4 on 2025-01-05 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_rename_depth_modelcharacteristics_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelcharacteristics',
            name='filling',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='modelcharacteristics',
            name='material_color',
            field=models.CharField(choices=[('Black', 'Чорний'), ('White', 'Білий'), ('Blue', 'Синій'), ('Red', 'Червоний'), ('Green', 'Зелений'), ('Yellow', 'Жовтий')], default='Black', max_length=10),
        ),
        migrations.AlterField(
            model_name='modelcharacteristics',
            name='material_type',
            field=models.CharField(choices=[('PLA', 'PLA'), ('ABS', 'ABS'), ('PETG', 'PETG'), ('Nylon', 'Nylon'), ('Resin', 'Resin'), ('Other', 'Інші')], default='PLA', max_length=10),
        ),
        migrations.AlterField(
            model_name='modelcharacteristics',
            name='post_processing',
            field=models.CharField(choices=[('None', 'Без обробки'), ('Sandblasting', 'Піскоструминна обробка'), ('Painting', 'Лакування'), ('Pre-Painting', 'Підготовка до фарбування')], default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='modelcharacteristics',
            name='resolution',
            field=models.CharField(choices=[('High', 'Висока'), ('Medium', 'Середня'), ('Low', 'Низька')], default='Medium', max_length=50),
        ),
        migrations.AlterField(
            model_name='modelcharacteristics',
            name='support_structure',
            field=models.CharField(choices=[('With Support', 'З підтримками'), ('Without Support', 'Без підтримок')], default='Without Support', max_length=50),
        ),
    ]
