# Generated by Django 5.1.4 on 2025-01-07 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_purchasedorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedorder',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
