# Generated by Django 5.1.4 on 2025-01-07 14:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_purchasedorder_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasedorder',
            name='purchased_at',
        ),
        migrations.AddField(
            model_name='purchasedorder',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Час створення'),
        ),
    ]
