# Generated by Django 5.1.4 on 2025-01-15 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_remove_order_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedorder',
            name='order_status',
            field=models.CharField(choices=[('created', 'Оформлено'), ('paid', 'Оплачено'), ('printing', 'Друкується'), ('shipped', 'Відправлено'), ('delivering', 'Доставляється'), ('delivered', 'Доставлено')], default='created', max_length=20, verbose_name='Статус замовлення'),
        ),
        migrations.AddField(
            model_name='purchasedorder',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Причина відмови'),
        ),
        migrations.AddField(
            model_name='purchasedorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Розглядається'), ('approved', 'Підтверджено'), ('rejected', 'Відхилено')], default='pending', max_length=10, verbose_name='Статус'),
        ),
    ]
