# Generated by Django 5.1.4 on 2025-01-22 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_purchasedorder_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelcharacteristics',
            name='post_processing',
            field=models.CharField(choices=[('None', 'Без обробки'), ('Sandblasting', 'Піскоструминна обробка'), ('Painting', 'Фарбування'), ('Pre-Painting', 'Підготовка до фарбування')], default='None', max_length=50),
        ),
    ]
