# Generated by Django 5.1.4 on 2025-01-22 21:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_modelcharacteristics_post_processing'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Час створення')),
                ('status', models.CharField(choices=[('pending', 'Розглядається'), ('approved', 'Підтверджено'), ('rejected', 'Відхилено')], default='pending', max_length=10, verbose_name='Статус')),
                ('order_status', models.CharField(choices=[('created', 'Оформлено'), ('paid', 'Оплачено'), ('printing', 'Друкується'), ('shipped', 'Відправлено'), ('delivering', 'Доставляється'), ('delivered', 'Доставлено')], default='created', max_length=20, verbose_name='Статус замовлення')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_info', to='orders.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_info_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата підтвердження')),
                ('order_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approval', to='orders.orderinfo')),
            ],
        ),
        migrations.CreateModel(
            name='OrderRejection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rejection_reason', models.TextField(verbose_name='Причина відмови')),
                ('rejection_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата відхилення')),
                ('order_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rejection', to='orders.orderinfo')),
            ],
        ),
        migrations.DeleteModel(
            name='PurchasedOrder',
        ),
    ]
