# Generated by Django 5.1.4 on 2025-01-23 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_orderinfo_orderapproval_orderrejection_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_type', models.CharField(choices=[('material', 'Матеріал'), ('post_processing', 'Постобробка'), ('urgency', 'Терміновість'), ('quality', 'Якість')], default='material', max_length=20, verbose_name='Тип параметра')),
                ('parameter_name', models.CharField(default='None', max_length=50, verbose_name='Назва параметра')),
                ('parameter_value', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Значення (ціна або множник)')),
            ],
        ),
        migrations.AddField(
            model_name='orderapproval',
            name='plastic_usage_per_file',
            field=models.JSONField(default=dict, verbose_name='Використання пластика для кожного файлу (в метрах)'),
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Загальна вартість'),
        ),
    ]
