# Generated by Django 5.1.4 on 2025-01-29 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_servicepricing_orderapproval_plastic_usage_per_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelcharacteristics',
            name='material_color',
        ),
        migrations.RemoveField(
            model_name='modelcharacteristics',
            name='material_type',
        ),
        migrations.AddField(
            model_name='modelcharacteristics',
            name='material',
            field=models.ForeignKey(blank=True, limit_choices_to={'parameter_type': 'material'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.servicepricing', verbose_name='Матеріал'),
        ),
    ]
