# Generated by Django 5.1.4 on 2025-01-29 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_remove_modelcharacteristics_material_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepricing',
            name='color',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Колір'),
        ),
    ]
