# Generated by Django 5.1.4 on 2025-02-19 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_servicepricing_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderapproval',
            name='plastic_usage_per_file',
        ),
    ]
