# Generated by Django 5.1.4 on 2025-02-19 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_remove_orderapproval_plastic_usage_per_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderapproval',
            name='plastic_usage_per_file',
            field=models.JSONField(default=dict, verbose_name='Використання пластика для кожного файлу (в метрах)'),
        ),
    ]
